### ISSUE TITLE
Client is not working

### ISSUE THREAD

**Issue by skhilav** [apsrcreatix/Socket-Programming-With-C#1]
The client is not working here. Repeated prints are coming.

**Comment by apsrcreatix** [comment]
Hey @skhilav 

You have not mentioned the file for which you need help.
Can you mention the problem in more detail so I can help?

Thanks,
Aditya Rajput

**Comment by FarshadKS** [comment]
I want to use server on my AWS instance. How can I modify IP address of server in client side?
